# Generated by Django 2.1 on 2018-08-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('backend', '0001_initial'), ('backend', '0002_auto_20180803_0411'), ('backend', '0003_auto_20180806_0353'), ('backend', '0004_auto_20180806_1422'), ('backend', '0005_streamendpoint_name'), ('backend', '0006_streamendpoint_owner')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='StreamEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restream',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile'),
        ),
        migrations.AlterField(
            model_name='restream',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='restream',
            name='lastStreamed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='restream',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamendpoint',
            name='restream',
            field=models.ManyToManyField(to='backend.Restream'),
        ),
        migrations.AddField(
            model_name='streamendpoint',
            name='name',
            field=models.CharField(default='Not Named', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamendpoint',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile'),
        ),
    ]
