# Generated by Django 2.1 on 2018-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_squashed_0006_streamendpoint_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restream',
            name='lastStreamed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamendpoint',
            name='restream',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Restream'),
        ),
    ]
