# Generated by Django 2.1 on 2018-08-24 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180812_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamendpoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='streamendpoint',
            name='restream',
            field=models.ManyToManyField(blank=True, to='backend.Restream'),
        ),
    ]
